Player stuck buffering for live streams
jwplayer/jwplayer-cast-receiver pull request #10
Opened 2017-03-29 16:25 UTC by hghazzi

Receiver was waiting for a `bufferChange` event to update the duration
and state, which does not occur with live streams. Replaced with `meta`
instead.

JW7-4214

2017-03-29 17:56 UTC, egreaves approved these changes

2017-03-29 18:25 UTC, egreaves requested changes

2017-03-29 18:25 UTC, egreaves commented on src/js/cast/mediamanager.js
> +                    if (!event.duration) {
Event duration may come later, so we should keep listening until we get it, then turn off the listener.

2017-03-29 20:40 UTC, egreaves approved these changes

2017-03-29 20:40 UTC, merged

2017-03-30 07:03 UTC, RikHeijdens commented on src/js/cast/mediamanager.js
> +                    console.log('onDuration');
Remove log?

2017-03-30 14:48 UTC, hghazzi commented
Thanks for catching that!

On Mar 30, 2017 3:03 AM, "Rik Heijdens" <notifications@github.com> wrote:

> *@RikHeijdens* commented on this pull request.
> ------------------------------
>
> In src/js/cast/mediamanager.js
> <https://github.com/jwplayer/jwplayer-cast-receiver/pull/10#discussion_r108853437>
> :
>
> >                  resolve();
>              } else {
> -            // Listen for the 'bufferChange' event in order the duration
> -            // before playback begins.
> -                playerInstance.once('bufferChange', event => {
> -                    mediaStatus.media.duration = event.duration;
> -                    resolve();
> -                });
> +                // Listen for the 'meta' event in order the duration
> +                // before playback begins.
> +                const onDuration = event => {
> +                    console.log('onDuration');
>
> Remove log?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jwplayer/jwplayer-cast-receiver/pull/10#pullrequestreview-29913286>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAjpdR_0AL7KQHUOQVZWyIpsLGGEN7E3ks5rq1O9gaJpZM4MtOd2>
> .
>